import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { GetStaticPropsContext } from "next";

import { useMemo } from "react";

import { QueryClient, dehydrate, useQuery } from "@tanstack/react-query";
import { getHeadlines } from "@/fetchers/getHeadlines/getHeadlines";

import { AVAILIBLE_COUNTRIES, CATEGORIES, PAGE_SIZE } from "@/common/constants";
import { CategoriesUnion, GetHeadlinesResponseType } from "@/types/common";

import styles from "./Category.module.scss";
import { useRouter } from "next/router";
import PaginationButton from "@/components/UI/PaginationButton/PaginationButton";
import { usePagination } from "@/hooks/usePagination";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { categoryName } = useRouter().query;

  const {
    page,
    hasNext,
    setHasNext,
    hasPrev,
    setHasPrev,
    handleNext,
    handlePrev,
  } = usePagination();

  const { data, isLoading } = useQuery<GetHeadlinesResponseType>(
    ["headlines_by_category", page],
    () =>
      getHeadlines({
        // safe type casting because we reroute to 404 if category is not in CATEGORIES
        category: categoryName as CategoriesUnion,
        pageSize: PAGE_SIZE,
        page,
        country: AVAILIBLE_COUNTRIES.UNITED_STATES,
      }),
    {
      onSuccess: (data) => {
        if (data?.totalResults) {
          setHasNext(data?.totalResults > page * PAGE_SIZE);
          setHasPrev(page > 1);
        }
      },
    }
  );

  // cleaning up the news api response.
  const articles = useMemo(() => {
    return data?.articles.filter((el) => {
      const filterConditions = [
        el.title === "[Removed]",
        el.content === "[Removed]",
        el.description === "[Removed]",
        el.urlToImage?.includes("www.si.com"),
      ];

      return !filterConditions.includes(true);
    });
  }, [data]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {articles?.map((article) => (
          <div key={article.source?.id || article?.publishedAt || article?.url}>
            <h1>{article?.title}</h1>
            <p>{article?.description}</p>
            {article?.urlToImage && (
              <div className={styles.imageContainer}>
                <Image
                  src={article?.urlToImage}
                  alt={article?.title || "Article Image"}
                  fill
                />
              </div>
            )}
          </div>
        ))}
        <PaginationButton disabled={!hasPrev} onClick={handlePrev}>
          Prev
        </PaginationButton>
        <PaginationButton disabled={!hasNext} onClick={handleNext}>
          Next
        </PaginationButton>
      </main>
    </>
  );
}

export async function getServerSideProps({ params }: GetStaticPropsContext) {
  const queryClient = new QueryClient();

  const category = params?.categoryName;

  // workaround for typescript's issue with Array.includes
  if (!CATEGORIES.includes(category as CategoriesUnion)) {
    return {
      redirect: {
        destination: "/404",
        permanent: false,
      },
    };
  }

  await queryClient.prefetchQuery(["headlines_by_category"], () =>
    // type casting is safe because we check if category is in CATEGORIES
    getHeadlines({
      category: category as CategoriesUnion,
      pageSize: PAGE_SIZE,
      country: AVAILIBLE_COUNTRIES.UNITED_STATES,
    })
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
