import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import { QueryClient, dehydrate, useQuery } from "@tanstack/react-query";
import { getHeadlines } from "@/fetchers/getHeadlines/getHeadlines";

import { AVAILIBLE_COUNTRIES, PAGE_SIZE } from "@/common/constants";
import { GetHeadlinesResponseType } from "@/types/common";

import styles from "@/styles/Home.module.scss";
import { usePagination } from "@/hooks/usePagination";
import PaginationButton from "@/components/UI/PaginationButton/PaginationButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const {
    page,
    setPage,
    hasNext,
    setHasNext,
    hasPrev,
    setHasPrev,
    handlePrev,
    handleNext,
  } = usePagination();

  const { data } = useQuery<GetHeadlinesResponseType>(
    ["all_headlines", page],
    () =>
      getHeadlines({
        country: AVAILIBLE_COUNTRIES.UNITED_STATES,
        pageSize: PAGE_SIZE,
        page,
      }),
    {
      onSuccess: (data: { totalResults: number }) => {
        if (data?.totalResults) {
          setHasNext(data?.totalResults > page * PAGE_SIZE);
          setHasPrev(page > 1);
        }
      },
    }
  );

  const articles = data?.articles;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {articles?.map((article) => (
          <div key={article.source?.id || article?.publishedAt || article?.url}>
            <h1>{article?.title}</h1>
            <p>{article?.description}</p>
            {article?.urlToImage && (
              <div className={styles.imageContainer}>
                <Image
                  src={article?.urlToImage}
                  alt={article?.title || "Article Image"}
                  fill
                />
              </div>
            )}
          </div>
        ))}
        <PaginationButton disabled={!hasPrev} onClick={handlePrev}>
          Prev
        </PaginationButton>
        <PaginationButton disabled={!hasNext} onClick={handleNext}>
          Next
        </PaginationButton>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(["all_headlines"], () =>
    getHeadlines({
      country: AVAILIBLE_COUNTRIES.UNITED_STATES,
      pageSize: PAGE_SIZE,
    })
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
