export const EVERY_COUNTRY_ENDPOINT = "/v2/countries";
export const TOP_HEADLINES_ENDPOINT = "/v2/top-headlines";
export const PAGE_SIZE = 10;

export const CATEGORIES = [
  "business",
  "entertainment",
  "general",
  "health",
  "science",
  "sports",
  "technology",
] as const;

export const AVAILIBLE_COUNTRIES = {
  UNITED_ARAB_EMIRATES: "ae",
  ARGENTINA: "ar",
  AUSTRIA: "at",
  AUSTRALIA: "au",
  BELGIUM: "be",
  BULGARIA: "bg",
  BRAZIL: "br",
  CANADA: "ca",
  SWITZERLAND: "ch",
  CHINA: "cn",
  COLOMBIA: "co",
  CUBA: "cu",
  CZECH_REPUBLIC: "cz",
  GERMANY: "de",
  EGYPT: "eg",
  FRANCE: "fr",
  UNITED_KINGDOM: "gb",
  GREECE: "gr",
  HONG_KONG: "hk",
  HUNGARY: "hu",
  INDONESIA: "id",
  IRELAND: "ie",
  ISRAEL: "il",
  INDIA: "in",
  ITALY: "it",
  JAPAN: "jp",
  SOUTH_KOREA: "kr",
  LITHUANIA: "lt",
  LATVIA: "lv",
  MOROCCO: "ma",
  MEXICO: "mx",
  MALAYSIA: "my",
  NIGERIA: "ng",
  NETHERLANDS: "nl",
  NORWAY: "no",
  NEW_ZEALAND: "nz",
  PHILIPPINES: "ph",
  POLAND: "pl",
  PORTUGAL: "pt",
  ROMANIA: "ro",
  SERBIA: "rs",
  RUSSIA: "ru",
  SAUDI_ARABIA: "sa",
  SWEDEN: "se",
  SINGAPORE: "sg",
  SLOVENIA: "si",
  SLOVAKIA: "sk",
  THAILAND: "th",
  TURKEY: "tr",
  TAIWAN: "tw",
  UKRAINE: "ua",
  UNITED_STATES: "us",
  VENEZUELA: "ve",
  SOUTH_AFRICA: "za",
} as const;
